name: Latest Blog Posts
on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://b143kc47.github.io/blog/feed.xml"
          max_post_count: 5
          template: "- **[$title]($url)** - $date"
          commit_message: "Update blog posts in README"
