name: Update Featured Projects

on:
  # 每周更新一次
  schedule:
    - cron: '0 0 * * 0'  # 每周日 UTC 时间 00:00
  
  # 在新的项目被标星或创建时更新
  repository_dispatch:
    types: [update-featured]
  
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  update-featured:
    name: Update Featured Projects in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub pandas markdown requests beautifulsoup4
          
      - name: Run Update Script
        run: python .github/scripts/update_featured_projects.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: B143KC47
          MAX_PROJECTS: 4
          SORT_BY: stars  # 可选: stars, updated, created, activity
          TOPICS_FILTER: "ai,machine-learning,deep-learning,nlp,computer-vision"
          EXCLUDE_REPOS: "dotfiles,notes,private-repo"
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "自动更新精选项目 [skip ci]"
          git push
