name: WakaTime Readme Stats

on:
  schedule:
    # 每天运行一次 (UTC 时间00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}    
          
          # 基本配置
          SHOW_LINES_OF_CODE: "True"  # 保留代码行数徽章
          SHOW_TOTAL_CODE_TIME: "True"  # 保留总编码时间
          
          # 启用美化的统计功能
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"  # 启用一周编码时间分布
          SHOW_LANGUAGE: "True"  # 启用编程语言统计
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"  # 启用编辑器使用统计
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "True"  # 启用简短信息
          SHOW_LOC_CHART: "True"  # 启用代码行数图表
          SHOW_UPDATED_DATE: "True"  # 显示更新时间
          
          # 区域设置
          LOCALE: "zh"
          
          # 输出格式设置
          IGNORED_REPOS: "*"  # 忽略所有仓库统计
          COMMIT_BY_ME: "False"  # 不显示提交信息
          

