name: 编码时间统计

on:
  workflow_dispatch:
  schedule:
    # 每天执行
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: 更新Readme的编码时间统计
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "zh"
